#!/usr/bin/env node

const S3Shell = require('./shell');
const S3Helper = require('./s3/s3Helper');
const AutoComplete = require('./autocomplete');
const { S3Client } = require("@aws-sdk/client-s3");
const prompt = require('./prompt');
const argv = require('minimist')(process.argv.slice(2));

const createShell = (profile, region) => {
  const client = new S3Client({ profile, region });
  const s3Helper = new S3Helper(client);
  return new S3Shell(s3Helper);
}

const run = async () => {
  const shell = createShell(argv.profile, argv.region);
  const autocomplete = new AutoComplete(shell);

  await shell.s3.checkCredentials();
  await prompt(shell, autocomplete);
};

if (require.main === module) {
  run();
}

module.exports = {
  createShell
};
