#!/usr/bin/env node

const S3Shell = require('./shell');
const s3Utils = require('./utils/s3utils');
const prompt = require('./prompt');

const run = async () => {
  const client = s3Utils.createClient();
  const shell = new S3Shell(client);

  await s3Utils.checkCredentials(client);
  await prompt(shell);
};

run();